# inference mode: text_prompt or reference_image
mode: text_prompt
# prediction confidence threshold
confidence_threshold: 0.1
# non-max suppression threshold
nms_threshold: 0.3
# text prompt, can consist of 1 or more queries (only for text_prompt mode)
text_queries:
- first query
- second query
# reference image id (only for reference_image mode)
reference_image_id: None
# object class name for labels (only for reference_image mode)
reference_class_name: None
# coordinates of bounding box on reference image (only for reference_image mode)
reference_bbox:
- y_min
- x_min
- y_max
- x_max